# Generated by Django 4.2.3 on 2023-11-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0014_staff_details_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules_list',
            name='Upi',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
